### ISSUE TITLE
Nette 2.3 incompatibility

### ISSUE THREAD

**Issue by frontycore** [mrtnzlml/monolog#1]
Looking really good, but incompatible with Nette 2.3 due to Nette\DI\Compiler::loadDefinitions(). This is rather question than an issue, will there be any support for Nette 2.3 in the future?

**Comment by mrtnzlml** [comment]
I have no problem with that (if it's still officially supported). I don't need it so I didn't add support for this Nette version but if you really want I'll do it. Now I am at vacation so let me know or send PR if you are able to do so. Thanks for understanding...
